(()=>{const q=s=>document.querySelector(s);document.querySelectorAll("[data-year]").forEach(el=>el.textContent=new Date().getFullYear());const toggle=q(".nav-toggle"),nav=q("#main-nav");if(toggle&&nav)toggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open))});const form=q("#interest-form"),status=q("#form-status");if(!form||!status)return;form.addEventListener("submit",async e=>{e.preventDefault();status.className="form-status";status.textContent="Sending…";const button=form.querySelector("button[type=submit]");button.disabled=true;const data=Object.fromEntries(new FormData(form).entries());try{const r=await fetch(form.action,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(data)});const result=await r.json().catch(()=>({}));if(!r.ok)throw new Error(result.error||"Unable to submit your interest at the moment.");form.reset();status.classList.add("success");status.textContent="Thank you. Your interest has been registered.";button.textContent="Interest registered"}catch(err){status.classList.add("error");status.textContent=err instanceof Error?err.message:"Unable to submit your interest at the moment.";button.disabled=false}})})();
(()=>{const buttons=[...document.querySelectorAll("[data-listen-target]")];if(!buttons.length)return;const synth=window.speechSynthesis,supported=synth&&"SpeechSynthesisUtterance" in window;if(!supported){buttons.forEach(b=>{b.disabled=true;b.textContent="Audio not supported on this device"});return}

let active=null,session=0,currentResolve=null;

const reset=()=>{buttons.forEach(b=>{b.textContent="▶ Listen to lesson";b.classList.remove("is-listening")});active=null};

const stop=()=>{session+=1;synth.cancel();if(currentResolve){const done=currentResolve;currentResolve=null;done()}reset()};

const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));

const chooseVoice=()=>{const voices=synth.getVoices().filter(v=>/^en(?:-|_)/i.test(v.lang||""));if(!voices.length)return null;const preferred=["Daniel","Samantha","Serena","Karen","Moira","Google UK English","Microsoft Sonia","Microsoft Ryan"];return voices.sort((a,b)=>{const score=v=>{let s=0;if((v.lang||"").toLowerCase()==="en-gb")s+=35;if(/natural|enhanced|premium|neural/i.test(v.name||""))s+=45;preferred.forEach((name,i)=>{if((v.name||"").toLowerCase().includes(name.toLowerCase()))s+=30-i});if(v.localService)s+=3;return s};return score(b)-score(a)})[0]||null};

const segmentsFrom=target=>{const segments=[];const add=(text,type="body")=>{text=(text||"").replace(/\s+/g," ").trim();if(text)segments.push({text,type})};[...target.children].forEach(el=>{const tag=el.tagName;if(/^H[1-6]$/.test(tag)){add(el.innerText,"heading");return}if(tag==="P"){add(el.innerText,"body");return}if(tag==="UL"||tag==="OL"){[...el.children].forEach((li,i)=>add((tag==="OL"?(i+1)+". ":"")+li.innerText,"list"));return}if(el.classList.contains("lesson-callout")){add(el.innerText,"callout");return}if(el.classList.contains("lesson-formula")){add(el.innerText,"formula");return}add(el.innerText,"body")});return segments};

const speakSegment=(segment,voice)=>new Promise(resolve=>{const u=new SpeechSynthesisUtterance(segment.text);u.lang="en-GB";if(voice)u.voice=voice;if(segment.type==="heading"){u.rate=.88;u.pitch=1.12}else if(segment.type==="formula"){u.rate=.86;u.pitch=1.03}else if(segment.type==="callout"){u.rate=.89;u.pitch=1.02}else{u.rate=.92;u.pitch=.99}u.volume=1;let finished=false;const done=()=>{if(finished)return;finished=true;if(currentResolve===done)currentResolve=null;resolve()};currentResolve=done;u.onend=done;u.onerror=done;synth.speak(u)});

const play=async(button)=>{stop();const mySession=++session;active=button;button.textContent="■ Stop listening";button.classList.add("is-listening");const target=document.querySelector(button.dataset.listenTarget);if(!target){reset();return}const voice=chooseVoice();const segments=segmentsFrom(target);for(let i=0;i<segments.length;i++){if(mySession!==session)return;const segment=segments[i];const previous=segments[i-1];if(segment.type==="heading"&&i>0)await wait(previous&&previous.type==="body"?520:380);if(mySession!==session)return;await speakSegment(segment,voice);if(mySession!==session)return;if(segment.type==="heading")await wait(320);else if(segment.type==="body")await wait(360);else if(segment.type==="list")await wait(180);else await wait(300)}if(mySession===session){session+=1;reset()}};

buttons.forEach(button=>button.addEventListener("click",()=>{if(active===button){stop();return}play(button)}));window.addEventListener("beforeunload",stop);if("onvoiceschanged" in synth)synth.onvoiceschanged=()=>synth.getVoices()})();
